name: Auto active github action after 2 months

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  auto_commit:
    name: 'Auto push a commit to my repo to keep github action available'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create sample file with just timestamp
      run: date +%s >> temp.txt
    - name: Commit file
      run: |
          git config --global user.name 'thanhdang198'
          git config --global user.email 'thanhdang198@users.noreply.github.com'
          git add temp.txt
          git commit -am "Automated activation github action"
          git push
