name: Hamster Kombat passive earn schedule
on: 
  schedule:
    - cron: '0 */2 * * *'
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦 huhihe
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://api.hamsterkombatgame.io/interlude/sync
          configuration: '{ "method": "POST", "headers": {"Authorization": "Bearer ${{ secrets.API_TOKEN }}"} }'
