name: Hamster Kombat passive earn schedule
on: 
  release:
    branches:
      - master
      - main
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://api.hamsterkombatgame.io/interlude/sync
          configuration: '{ "method": "POST", "headers": {"Authorization": "Bearer ${{ secrets.API_TOKEN }}"} }'